In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('C:/Users/Khaled/Documents/CV Course/1/Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',') 
# generate text from csv file

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
# split train and test data

In [12]:
len(X_train)

919

In [13]:
len(X)

1372

In [14]:
len(X_test)

453

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
scalar_object = MinMaxScaler()
# create max min scaler object

In [18]:
scalar_object.fit(X_train)
# fit data on the train dataset

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scalar_object.transform(X_train)
# scale data on the train dataset

In [20]:
scaled_X_test = scalar_object.transform(X_test)

In [21]:
scaled_X_train.max()

1.0000000000000002

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model = Sequential()
# create a model

model.add(Dense(4,input_dim=4,activation='relu'))
# add input neural network layer

model.add(Dense(10,activation='relu'))
# add intermediate neural layer

model.add(Dense(1,activation='sigmoid'))
# add output neural network layer

In [39]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
# compile the model

In [40]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)
# train the dataset

Epoch 1/50
 - 1s - loss: 0.6875 - acc: 0.5898
Epoch 2/50
 - 0s - loss: 0.6841 - acc: 0.6181
Epoch 3/50
 - 0s - loss: 0.6794 - acc: 0.6289
Epoch 4/50
 - 0s - loss: 0.6738 - acc: 0.6268
Epoch 5/50
 - 0s - loss: 0.6672 - acc: 0.6333
Epoch 6/50
 - 0s - loss: 0.6511 - acc: 0.6855
Epoch 7/50
 - 0s - loss: 0.6220 - acc: 0.7182
Epoch 8/50
 - 0s - loss: 0.5957 - acc: 0.7280
Epoch 9/50
 - 0s - loss: 0.5737 - acc: 0.7323
Epoch 10/50
 - 0s - loss: 0.5553 - acc: 0.7454
Epoch 11/50
 - 0s - loss: 0.5367 - acc: 0.7552
Epoch 12/50
 - 0s - loss: 0.5186 - acc: 0.7671
Epoch 13/50
 - 0s - loss: 0.5021 - acc: 0.7813
Epoch 14/50
 - 0s - loss: 0.4871 - acc: 0.7933
Epoch 15/50
 - 0s - loss: 0.4722 - acc: 0.8020
Epoch 16/50
 - 0s - loss: 0.4577 - acc: 0.8063
Epoch 17/50
 - 0s - loss: 0.4428 - acc: 0.8215
Epoch 18/50
 - 0s - loss: 0.4309 - acc: 0.8324
Epoch 19/50
 - 0s - loss: 0.4168 - acc: 0.8390
Epoch 20/50
 - 0s - loss: 0.4026 - acc: 0.8509
Epoch 21/50
 - 0s - loss: 0.3896 - acc: 0.8640
Epoch 22/50
 - 0s - lo

In [27]:
# model.predict_classes(scaled_X_test)
# use the testing data to test the trained model

In [28]:
model.metrics_names
# get the metrics

['loss', 'acc']

In [29]:
from sklearn.metrics import confusion_matrix,classification_report

In [31]:
predictions = model.predict_classes(scaled_X_test)
# use the testing data to test the trained model

In [41]:
confusion_matrix(y_test,predictions)
# display the confusion matrix

array([[250,   7],
       [ 14, 182]], dtype=int64)

In [42]:
print(classification_report(y_test,predictions))
# display the classification report

             precision    recall  f1-score   support

        0.0       0.95      0.97      0.96       257
        1.0       0.96      0.93      0.95       196

avg / total       0.95      0.95      0.95       453



In [43]:
model.save('money.h5')
# save the model

In [44]:
from keras.models import load_model

In [45]:
newmodel = load_model('money.h5')
# import the model

In [47]:
# newmodel.predict_classes(scaled_X_test)